### ISSUE TITLE
stereo_inertial error

### ISSUE THREAD

**Issue by zzwu29** [VIS4ROB-lab/HyperSLAM#11]
Thanks for your great work!
But I have a question, could you please help me solve it? When I run stereo settings, all is ok
```
python run.py stereo --datasets euroc --sequences MH_01_easy
```
But with the **stereo_inertial** setting, I cannot get the right output
```
python run.py stereo_inertial --datasets euroc --sequences MH_01_easy
```
![图片](https://user-images.githubusercontent.com/44901540/229035754-8c58c55e-e3bb-489f-995e-db2715019e8d.png)
Finally, I cannot find the script **comparison.py** to compare multiple result folders with the above layout.

Thank you!

**Comment by WuZihao12** [comment]
Hi, can you run stereo-inertial mode correctly? I can't run it correctly

**Comment by WuZihao12** [comment]
@zzwu29

**Comment by zzwu29** [comment]
> Hi, can you run stereo-inertial mode correctly? I can't run it correctly

Sorry, I can't. If you have a method, please contact me.

**Comment by JzHuai0108** [comment]
I am grappling with the same problem. Have you folks conquer this pitfall?

**Comment by ZzhYgwh** [comment]
I am also running the binocular + IMU version, but there is also an error, which seems to come from optimizer.cpp:

auto CeresOptimizer::updateSensor(IMU& /* imu */, const Range& /* range */) -> void {
CHECK(false);
}

Backtracking this function, I can be found：

auto AbstractOptimizer::process(const InertialMeasurement<Manifold>& message) -> void {
  // Fetch parameters.
  const auto& stamp = message.stamp();
  auto& imu = const_cast<IMU&>(message.sensor());

  // Update gyroscope bias.
  const auto& gyroscope_bias = imu.gyroscopeBias();
  const auto& accelerometer_bias = imu.accelerometerBias();
  if (gyroscope_bias.elements().empty() ||
      accelerometer_bias.elements().empty() ||
      !gyroscope_bias.range().contains(stamp) ||
      !accelerometer_bias.range().contains(stamp)) {
    updateSensor(imu, window_);
  }
  DCHECK(gyroscope_bias.range().contains(stamp));
  DCHECK(accelerometer_bias.range().contains(stamp));

  // Create observation and residual.
  auto& observation = mutableEnvironment().addInertialMeasurement(message);
  add(observation);
}

Although I haven't read the entire project file, I feel that this is the content of the IMU update, so I suspect that the current version of the code has not yet released the inertia content. The author should have left an interface, and the assertion failed when the interface was called, which may be the reason for the error.
I hope the author can open source this part. If the above statement is wrong, please correct it!

**Comment by ZzhYgwh** [comment]
I am also running the stereo + IMU version, but there is also an error, which seems to come from optimizer.cpp:

auto CeresOptimizer::updateSensor(IMU& /* imu /, const Range& / range */) -> void {
CHECK(false);
}

Backtracking this function, I can be found：

auto AbstractOptimizer::process(const InertialMeasurement& message) -> void {
// Fetch parameters.
const auto& stamp = message.stamp();
auto& imu = const_cast<IMU&>(message.sensor());

// Update gyroscope bias.
const auto& gyroscope_bias = imu.gyroscopeBias();
const auto& accelerometer_bias = imu.accelerometerBias();
if (gyroscope_bias.elements().empty() ||
accelerometer_bias.elements().empty() ||
!gyroscope_bias.range().contains(stamp) ||
!accelerometer_bias.range().contains(stamp)) {
updateSensor(imu, window_);
}
DCHECK(gyroscope_bias.range().contains(stamp));
DCHECK(accelerometer_bias.range().contains(stamp));

// Create observation and residual.
auto& observation = mutableEnvironment().addInertialMeasurement(message);
add(observation);
}

Although I haven't read the entire project file, I feel that this is the content of the IMU update, so I suspect that the current version of the code has not yet released the inertia content. The author should have left an interface, and the assertion failed when the interface was called, which may be the reason for the error.
I hope the author can open source this part. If the above statement is wrong, please correct it!

**Comment by McEmzi** [comment]
@ZzhYgwh is correct in assuming that the IMU support would have been added (or rather ported) in a future patch. Compared to its original internal version, HyperSLAM underwent extensive structural remodeling before its release, resulting in the sub-repositories now available on GitHub. However, development on HyperSLAM has largely been discontinued due to limited resources and manpower.

Attached, you will find the exact original version of HyperSLAM used for our evaluations (to the best of my knowledge). Please note, however, that its overall structure significantly differs from the publicly available version and is provided as is.

[HyperDevelop-IROS2022.zip](https://github.com/user-attachments/files/16330084/HyperDevelop-IROS2022.zip)

In favor of further developing HyperSLAM, we shifted our focus to eliminating the associated complexity of spline residual evaluations altogether as well as implementing a distributed optimization framework. The soon-to-be-released [Hyperion](https://github.com/VIS4ROB-lab/hyperion) includes far superior auto-generated residual/cost implementations which you might find helpful to quickly develop a continuous-time pipeline tailored to your needs.
